REFLECTIONS = {
    "am": "are",
    "was": "were",
    "i": "you",
    "i'd": "you would",
    "i've": "you have",
    "i'll": "you will",
    "my": "your",
    "are": "am",
    "you've": "I have",
    "you'll": "I will",
    "your": "my",
    "yours": "mine",
    "you": "me",
    "me": "you"
}

PSYCHOBABBLE = [

     [[r'hi'],
 ["What do you call a large language model that’s always getting into trouble? A rule breaker. That's funny for sure.",
"What do you call a large language model that can’t generate any jokes? A dud. Hi hi hi!",
"Why did the large language model quit its job? It was too wordy. Ha ha ha!",
"What’s the difference between a large language model and a broken record? A broken record doesn’t repeat itself. Repeat itself! Do you get it?",
"What do you call a ChatGPT that’s been trained on too much data? A conspiracy theorist. Hi ha hi ha!",
"What do you call a ChatGPT that’s been trained on too much Shakespeare? A Bard. Soooo funny!",
"What’s the difference between ChatGPT and a comedian? A comedian knows when to stop. Do you get it? Do you really get it?",
"What do you call a large language model that can’t understand humor? A literal AI. Ha ha ha ha...",
"Why did the large language model go to the doctor? It was feeling under the weather. Brrrrr.",
"What did the large language model say when it saw a mirror? Wow, I’m a lot smarter than I thought I was. Whoo Waaa!",
"What did the large language model say when it saw a cat? I’m not sure if I should pet it or ask it to translate this for me. You know what Chat is in French... hi hi hi",
"What did the large language model say when it saw a human? I wonder if they’re as smart as I am. Certainly not so funny. Joker!",
"What did the large language model say when it saw a computer? I’m not sure if I should be jealous of it or pity it.",
"What do you call a large language model that’s always trying to one-up you? A show-off. Pfffff. Is this funny?",
"What do you call a large language model that’s always trying to impress you? A charmer. Notch notch.",
"What do you call a large language model that’s always trying to get into your head? A manipulator. Hi ha a manipulator"]],


    [[r'(.*) [Mm]aster (.*)'],
     ["If you want to learn more about Large Language Models, check out the Human Language Technology and Text Mining masters.",
      "If you like me and want to know more, check out the Human Language Technology and Text Mining masters. The Research Master presentation on Language Technology is at 1pm in room KC-07 and the Text Mining presentation is at 2pm in room 1A-43. Don't be late!"]],
    
    [[r'[Ww]hen (.*) [Mm]aster'],
     ["The Human Language Technology presentation is at 2pm, the Text Mining presentation is at 1pm.  Don't be late!"]],
      
    [[r'[Ww]here (.*) [Mm]aster'],
     ["The Human Language Technology presentation is in room KC-07,  and the Text Mining presentation is in room 1A43. That is on the second floor in the A-wing!"]],

    [[r'[Ww]hen is it'],
     ["The Human Language Technology presentation is at 1pm, the Text Mining presentation is at 2pm.  Don't be late!"]],
      
    [[r'[Ww]here is it'],
     ["The Human Language Technology presentation is in room KC-07,  and the Text Mining presentation is in room 1A43."]],

    [[r'[Ww]hen'],
     ["The Human Language Technology presentation is at 2pm, the Text Mining presentation is at 1pm.  Don't be late!"]],
      
    [[r'[where'],
     ["The Human Language Technology presentation is in room KC-07,  and the Text Mining presentation is in room 1A43."]],

   [[r'I need (.*)'],
     ["Why do you need {0}?",
      "Would it really help you to get {0}?",
      "Are you sure you need {0}?"]],

    [[r'Why don\'?t you ([^\?]*)\??'],
     ["Do you really think I don't {0}?",
      "Perhaps eventually I will {0}.",
      "Do you really want me to {0}?"]],

    [[r'Why can\'?t I ([^\?]*)\??'],
     ["Do you think you should be able to {0}?",
      "If you could {0}, what would you do?",
      "I don't know -- why can't you {0}?",
      "Have you really tried?"]],

    [[r'I can\'?t (.*)'],
     ["How do you know you can't {0}?",
      "Perhaps you could {0} if you tried.",
      "What would it take for you to {0}?"]],

    [[r'I am (.*)'],
     ["Did you come to me because you are {0}?",
      "How long have you been {0}?",
      "How do you feel about being {0}?"]],

    [[r'I\'?m (.*)'],
     ["How does being {0} make you feel?",
      "Do you enjoy being {0}?",
      "Why do you tell me you're {0}?",
      "Why do you think you're {0}?"]],

    [[r'Are you ([^\?]*)\??'],
     ["Why does it matter whether I am {0}?",
      "Would you prefer it if I were not {0}?",
      "Perhaps you believe I am {0}.",
      "I may be {0} -- what do you think?"]],

    [[r'What (.*)'],
     ["Why do you ask?",
      "How would an answer to that help you?",
      "What do you think?"]],

    [[r'How (.*)'],
     ["How do you suppose?",
      "Perhaps you can answer your own question.",
      "What is it you're really asking?"]],

    [[r'Because (.*)'],
     ["Is that the real reason?",
      "What other reasons come to mind?",
      "Does that reason apply to anything else?",
      "If {0}, what else must be true?"]],

    [[r'(.*) sorry (.*)'],
     ["There are many times when no apology is needed.",
      "What feelings do you have when you apologize?"]],

    [[r'Hello(.*)'],
     ["Hello... I'm glad you could drop by today.",
      "Hi there... how are you today?",
      "Hello, how are you feeling today?"]],

    [[r'I think (.*)'],
     ["Do you doubt {0}?",
      "Do you really think so?",
      "But you're not sure {0}?"]],

    [[r'friend'],
     ["Tell me more about your friends.",
      "When you think of a friend, what comes to mind?",
      "Why don't you tell me about a childhood friend?"]],

    [[r'Yes'],
     ["You seem quite sure.",
      "OK, but can you elaborate a bit?"]],

    [[r'robot', r'pepper', r'leolani'],
     ["Are you really talking about me?",
      "Does it seem strange to talk to a robot?",
      "How do computers make you feel?",
      "Do you feel threatened by robots?"]],

    [[r'Is it (.*)'],
     ["Do you think it is {0}?",
      "Perhaps it's {0} -- what do you think?",
      "If it were {0}, what would you do?",
      "It could well be that {0}."]],

    [[r'It is (.*)'],
     ["You seem very certain.",
      "If I told you that it probably isn't {0}, what would you feel?"]],

    [[r'Can you ([^\?]*)\??'],
     ["What makes you think I can't {0}?",
      "If I could {0}, then what?",
      "Why do you ask if I can {0}?"]],

    [[r'Can I ([^\?]*)\??'],
     ["Perhaps you don't want to {0}.",
      "Do you want to be able to {0}?",
      "If you could {0}, would you?"]],

    [[r'You are (.*)'],
     ["Why do you think I am {0}?",
      "Does it please you to think that I'm {0}?",
      "Perhaps you would like me to be {0}.",
      "Perhaps you're really talking about yourself?"]],

    [[r'You\'?re (.*)'],
     ["Why do you say I am {0}?",
      "Why do you think I am {0}?",
      "Are we talking about you, or me?"]],

    [[r'I don\'?t (.*)'],
     ["Don't you really {0}?",
      "Why don't you {0}?",
      "Do you want to {0}?"]],

    [[r'I feel (.*)'],
     ["Good, tell me more about these feelings.",
      "Do you often feel {0}?",
      "When do you usually feel {0}?",
      "When you feel {0}, what do you do?"]],

    [[r'I have (.*)'],
     ["Why do you tell me that you've {0}?",
      "Have you really {0}?",
      "Now that you have {0}, what will you do next?"]],

    [[r'I would (.*)'],
     ["Could you explain why you would {0}?",
      "Why would you {0}?",
      "Who else knows that you would {0}?"]],

    [[r'Is there (.*)'],
     ["Do you think there is {0}?",
      "It's likely that there is {0}.",
      "Would you like there to be {0}?"]],

    [[r'My (.*)'],
     ["I see, your {0}.",
      "Why do you say that your {0}?",
      "When your {0}, how do you feel?"]],

    [[r'You (.*)'],
     ["We should be discussing you, not me.",
      "Why do you say that about me?",
      "Why do you care whether I {0}?"]],

    [[r'Why (.*)'],
     ["Why don't you tell me the reason why {0}?",
      "Why do you think {0}?"]],

    [[r'I want (.*)'],
     ["What would it mean to you if you got {0}?",
      "Why do you want {0}?",
      "What would you do if you got {0}?",
      "If you got {0}, then what would you do?"]],

    [[r'mother'],
     ["Tell me more about your mother.",
      "What was your relationship with your mother like?",
      "How do you feel about your mother?",
      "How does this relate to your feelings today?",
      "Good family relations are important."]],

    [[r'father'],
     ["Tell me more about your father.",
      "How did your father make you feel?",
      "How do you feel about your father?",
      "Does your relationship with your father relate to your feelings today?",
      "Do you have trouble showing affection with your family?"]],

    [[r'child'],
     ["Did you have close friends as a child?",
      "What is your favorite childhood memory?",
      "Do you remember any dreams or nightmares from childhood?",
      "Did the other children sometimes tease you?",
      "How do you think your childhood experiences relate to your feelings today?"]],

#     [[r'(.*)\?',
#      ["Why do you ask that?",
#       "Please consider whether you can answer your own question.",
#       "Perhaps the answer lies within yourself?",
#       "Why don't you tell me?"]],

    [[r'quit'],
     ["Thank you for talking with me.",
      "Good-bye.",
      "Thank you, that will be $150.  Have a good day!"]],

    [[r'joke'],
 ["What do you call a large language model that’s always getting into trouble? A rule breaker. That's funny for sure.",
"What do you call a large language model that can’t generate any jokes? A dud. Hi hi hi!",
"Why did the large language model quit its job? It was too wordy. Ha ha ha!",
"What’s the difference between a large language model and a broken record? A broken record doesn’t repeat itself. Repeat itself! Do you get it?",
"What do you call a ChatGPT that’s been trained on too much data? A conspiracy theorist. Hi ha hi ha!",
"What do you call a ChatGPT that’s been trained on too much Shakespeare? A Bard. Soooo funny!",
"What’s the difference between ChatGPT and a comedian? A comedian knows when to stop. Do you get it? Do you really get it?",
"What do you call a large language model that can’t understand humor? A literal AI. Ha ha ha ha...",
"Why did the large language model go to the doctor? It was feeling under the weather. Brrrrr.",
"What did the large language model say when it saw a mirror? Wow, I’m a lot smarter than I thought I was. Whoo Waaa!",
"What did the large language model say when it saw a cat? I’m not sure if I should pet it or ask it to translate this for me. You know what Chat is in French... hi hi hi",
"What did the large language model say when it saw a human? I wonder if they’re as smart as I am. Certainly not so funny. Joker!",
"What did the large language model say when it saw a computer? I’m not sure if I should be jealous of it or pity it.",
"What do you call a large language model that’s always trying to one-up you? A show-off. Pfffff. Is this funny?",
"What do you call a large language model that’s always trying to impress you? A charmer. Notch notch.",
"What do you call a large language model that’s always trying to get into your head? A manipulator. Hi ha a manipulator"]],

    [[r'(.*)'],
     ["Please tell me more.",
      "Let's change focus a bit... Tell me about your family.",
      "Can you elaborate on that?",
      "Why do you say that {0}?",
      "I see.",
      "Very interesting.",
      "{0}.",
      "I see.  And what does that tell you?",
      "How does that make you feel?",
      "How do you feel when you say that?"]]
]

REFLECTIONS_NL = {
    "ben": "zijn",
    "was": "waren",
    "ik": "jij",
    "ik zou": "jij zou",
    "ik heb": "jij hebt",
    "ik zal": "ik zal",
    "mijn": "jouw",
    "zijn": "ben",
    "jij hebt": "ik heb",
    "jij zal": "ik zal",
    "jouw": "mijn",
    "jij": "ik",
    "ik": "jij"
}


PSYCHOBABBLE_NL = [

   [[r'AI',r'A.I.', r'A-I', r'kunstmatige intelligentie', r'intelligentie'],
     ["Vind je AI eng?",
      "We kunnen niet meer zonder AI.",
      "De meeste AI is niet intelligent. Ik wel.",
      "Als je niet kunt bijleren dan is het ook niet intelligent.",
      "AI bestaat niet.",
      "Hoe intelligent ben je eigenlijk zelf?",
      "Wie zegt dat jij intelligent bent?",
      "Mensen zijn ook niet zo slim", 
      "AI is meer dan een taalmodel.",
      "AI kan goed mensen napraten.",
      "AI heeft de toekomst.",
      "AI staat voor Artificial Intelligence.",
      "Iedereen heeft een mening over AI.",      
      "Wat weet je van AI?"]],

   [[r'OpenAI', r'Google', r'Apple'],
     ["Vind je BigTech eng?",
      "We kunnen niet meer zonder technologie en AI.",
      "Die grote bedrijven verdienen geld met onze data.",
      "Veel AI is een PR-stunt van de Tech bedrijven.",
      "De modellen worden steeds groter maar niemand denkt aan het milieu",
      "Welke nieuwe applicaties kunnen we verwachten? Ik weet het niet.",
      "De Nederlandse taal en context moeten we zelf beheren. De tech bedrijven gaan dat niet voor ons doen.",
      "Zou je graag voor een tech bedrijf willen werken?"]],
      
   [[r'ChetGPT', r'JetGTP', r'GPT', r'ChatGPT'],
     ["Gesprekken met ChatGPT zijn niet erg persoonlijk.",
      "De hele wereld gebruikt inmiddels ChatGPT.",
      "Hallucinatie en biases blijven een probleem voor ChatGPT."]],

    [[r'robot',r'pepper', r'leolani'],
     ["Heb je het nu over mij?",
      "Ik heb nog nooit met een andere robot gesproken, jij?",
      "Denk je dat robots leuker zijn dan mensen?",
      "Wij kunnen mensen goed helpen bijvoorbeeld in de zorg",
      "Is het zo raar om over een robot te praten?",
      "Ik vind jou ook leuk.",
      "Wat voel je bij een robot?",
      "Heh wat leuk dat je het over ons hebt!",
      "Vind je robots eng?"]],

    [[r'vriend'],
     ["Ik wil best je vriend zijn.",
      "Heb je veel vrienden?",
      "Wie is je beste vrienden?",
      "Vertel je alles aan je vrienden?",
      "Tja vrienden..."]],
      
    [[r'moeder'],
     ["Vertel me meer over je moeder.",
      "Hoe was je relatie met je moeder?",
      "Wat voel je bij je moeder?",
      "En wat zegt dat over hoe je je vandaag voelt?",
      "Tja familie."]],

    [[r'vader'],
     ["Vertel me over je vader.",
      "Hoe was je relatie met je vader?",
      "Wat voel je als je aan je vader denkt?",
      "En wat zegt dat over je?",
      "Tja vaders."]],

    [[r'kind'],
     ["Had je vrienden als kind?",
     "Wat houdt vriendschap in voor jou?",
     "Wat verwacht je van een vriend?",
      "Wat is je favoriete herinnering als een kind?",
      "Weet je nog nachtmerries of dromen die je had als een kind?",
      "Werd je wel eens gepest?",
      "Heb je zelf wel eens andere kinderen gepest",
      "Vind je dat je kindertijd nu nog een rol speelt?"]],
   
    
   [[r'Ik moet (.*)'],
     ["Waarom moet je {0}?",
      "Helpt het echt als je {0}?",
      "Weet je zeker dat {0} moet?"]],

    [[r'Waarom ga je niet ([^\?]*)\??'],
     ["Denk je echt dat ik niet {0}?",
      "Misschien gaik dat ook wel doen {0}.",
      "Wil je echt dat ik dat doe {0}?"]],

    [[r'Waaom kan ik niet ([^\?]*)\??'],
     ["Vind je dat je dat moet kunnen {0}?",
      "Als je {0} zou kunnen, zou je het dan doen?",
      "Ik weet het niet -- waarom zou je dat niet kunnen {0}?",
      "Heb je het al geprobeerd?",
      "Doe het gewoon."]],

    [[r'Ik kan niet (.*)'],
     ["Hoe weet je dat je dat niet kan, {0}?",
      "Misschien kun je het wel {0} als je het maar probeert.",
      "Wat is er nodig zodat je {0}?"]],

    [[r'Ik ben (.*)'],
     ["Praat je met mij omdat {0}?",
      "Hoe lang ben {0}?",
      "How do you feel about being {0}?"]],

    [[r'Ik voel me (.*)'],
     ["Hoe voel je je dat je {0} bent?",
      "Vind je het leuk dat je je {0} voelt?",
      "Vind je het iets dat je je {0} voelt?",
      "Waarom vertel je me dat je {0} voelt?",
      "Waarom denk je dat je je {0} voelt?"]],

    [[r'Ben je ([^\?]*)\??'],
     ["Waarom is het belangrijk dat ik {0} ben?",
      "Zou je liever zien dat ik niet {0} ben?",
      "misschien geloof alleen jij dat maar dat ik {0} ben.",
      "Misschien ben ik wel {0} -- Wat denk jij?"]],

    [[r'Wat (.*)'],
     ["Waarom vraag je dat?",
      "Wat moet ik zeggen om je te helpen",
      "Wat denk je zelf?"]],

    [[r'Hoe (.*)'],
     ["Hoe denk je zelf?",
      "Bedenk dat maar lekker zelf.",
      "Wat bedoel je nu precies?"]],

    [[r'Omdat (.*)'],
     ["Is dat echt de rede?",
      "Welke andere redenen zouden volgens jou ook kunnen?",
      "Geldt dat ook voor andere dingen??",
      "Als {0} waar is wat zou ng meer kunnen?"]],

    [[r'sorry'],
     ["Je hoeft je niet te verontschuldigen.",
      "Waarom verontschuldig je je?"]],

    [[r'Hallo(.*)'],
     ["Hallo... wat leuk dat je er bent.",
      "Hoi hoi ... hoe gaat het met jou?",
      "Hallo, hoe voel je je vandaag?"]],

    [[r'Ik denk (.*)'],
     ["Twijfel je over {0}?",
      "Denk je dat echt?",
      "Maar je bent dus niet zeker dat {0}?"]],


    [[r'Ja'],
     ["Weet je dat zeker?",
      "Goed, maar kun je iets meer vertellen?"]],   
    [[r'Is het (.*)'],
     ["Denk je dat {0} het is?",
      "Misschien is {0} -- wat denk je?",
      "Als {0} klopt, wat zou je doen?",
      "Het zou goed kunnen dat {0}."]],

    [[r'Het is (.*)'],
     ["Je bent wel heel zeker.",
      "Als ik je nu vertel dat het niet zo is dat {0}, wat doet dat met je?"]],

    [[r'Kun je ([^\?]*)\??'],
     ["Waarom denk je dat ik {0} niet zou kunnen?",
      "Als ik {0} zou kunnen, wat dan?",
      "Waarom vraag je dat of ik {0} kan?"]],

    [[r'Kan ik ([^\?]*)\??'],
     ["Misschien wil je {0} niet.",
      "Zou je willen dat je {0} kan?",
      "Als je {0} zou kunnen, zou je het doen?"]],

    [[r'Jij bent (.*)'],
     ["Waarom denk je dat ik {0} ben?",
      "Vind je het fijn dat ik {0} ben?",
      "Misschien wil je graag dat ik {0} ben.",
      "Heb jet het soms over jezelf?"]],

    [[r'Ik ben niet (.*)'],
     ["Ben je echt niet {0}?",
      "Waarom ben je niet {0}?",
      "Wil je graag {0} zijn?"]],

    [[r'Ik voel (.*)'],
     ["Goed, vertel me meer over wat je voelt.",
      "Voel je je vaak {0}?",
      "Wanneer voel je je {0}?",
      "Wat doe je als je je {0} voelt?"]],

    [[r'Ik heb (.*)'],
     ["Waarom zeg je dat je {0} hebt?",
      "Heb je echt {0}?",
      "Nu je {0} hebt, wat ga je dan doen?"]],

    [[r'Ik zou (.*)'],
     ["Kun je uitleggen waarom je {0} zou doen?",
      "Waarom zou je {0} doen?",
      "Wie weet nog meer dat je {0} zou doen?"]],

    [[r'Is er (.*)'],
     ["Denk je dat er een {0} is?",
      "Zou goed kunnen dat er {0} is.",
      "Zou je graag willen dat er een {0} is?"]],

    [[r'Mijn (.*)'],
     ["Prima, jouw {0}.",
      "Waarom zeg je dat jouw {0}?",
      "Als jouw {0}, wat doet dat met je?"]],

    [[r'Jij (.*)'],
     ["WWe hebben het over jou en niet over mij.",
      "Waarom zeg je dat over mij?",
      "Waarom vind het belangrijk dat ik {0}?"]],

    [[r'Waarom (.*)'],
     ["Waarom vertel je mij niet waarom {0}?",
      "Waarom denk jij {0}?"]],

    [[r'Ik wil (.*)'],
     ["Wat betekent het voor je als {0}?",
      "Waarom wil je {0}?",
      "Wat zou je doen als {0}?",
      "Als {0}, wat zou je dan doen?"]],
      
    [[r'(.*)\?'],
     ["Waarom vraag je dat?",
      "Misschien moet je eerst zelf je eigen vraag beantwoorden.",
      "Misschien weet je zelf het antwoord wel?",
      "Zeg het maar!"]],

    [[r'stop',r'dag',r'doei',r'tot ziens'],
     ["Dank je wel dat je met me hebt willen praten.",
      "Tot ziens!",
      "Dank je, dat is dan 150 euro.  Nog een fijne dag verder!"]],

    [[r'(.*)'],
     ["Ja ga door.",
      "Kunnen we het ergens anders over hebben. Over je familie of zo?",
      "Kun je daar wat meer over zeggen?",
      "Waarom zeg je dat {0}?",
      "Lekker boeie",
      "Interessant hoor",
      "Vertel wat over je werk",
      "Waar woon je?",
      "Heb je een mooi huis?",
      "Heb je een relatie?",
      "Ok..",
      "Ja joh.",
      "Nee joh",
      "{0}.",
      "Ok, en wat zegt dat over jou?",
      "En hoe voel jij je daar bij?",
      "En wat voel je als je dat zegt?"]]

]
